### ISSUE TITLE
Remote class should use CIDs

### ISSUE THREAD

**Issue by expede** [fission-suite/ipfs-haskell#5]
## Problem

Right now, the remote class accepts arbitrary `Text`. Both for reasons of documentation, and ensuring that we're expressing our intent, this should be strengthened at the type level.

## Solution

Use the existing CID type `newtype CID = CID { unaddress :: Text }`

```haskell
  ipfsCat   :: Text            -> m (Either ClientError File.Serialized)
  ipfsPin   :: Text            -> m (Either ClientError Pin.Response)
  ipfsUnpin :: Text -> Bool    -> m (Either ClientError Pin.Response)
```

should read

```haskell
  ipfsCat   :: CID            -> m (Either ClientError File.Serialized)
  ipfsPin   :: CID            -> m (Either ClientError Pin.Response)
  ipfsUnpin :: CID -> Bool    -> m (Either ClientError Pin.Response)
```

**Comment by dholms** [comment]
Fixed in https://github.com/fission-suite/ipfs-haskell/pull/6
